### ISSUE TITLE
How to flash

### ISSUE THREAD

**Issue by DAChT98** [Xinyuan-LilyGO/T-SIM7600X#18]
Hi, I need help with the Download Tools V3.9.2. I cannot upload the firmware.

**Comment by LilyGO** [comment]
Hello，Have you ever burned with arduinoIDE?

**Comment by DAChT98** [comment]
> Hello，Have you ever burned with arduinoIDE?

nope, could you help me?

**Comment by LilyGO** [comment]
[steps](https://github.com/Xinyuan-LilyGO/LilyGo-T-PCIE#1steps) ,  [example]( https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7600X/tree/master/examples)
