### ISSUE TITLE
How can I access the SPK and MIC pins with this board? 

### ISSUE THREAD

**Issue by contractorwolf** [Xinyuan-LilyGO/T-SIM7600X#31]
I see the pins in the interface schematics but I am unsure of how I can access them.  Are they mapped or labels somewhere?

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/224736574-c47cafc3-aea6-4aba-8578-0585e7eb5cd2.png)
You need to make sure that your board has an audio decoding chip, otherwise it cannot be used

**Comment by contractorwolf** [comment]
Where can I buy the one with the audio board?

**Comment by lewisxhe** [comment]
When purchasing, you can explain to the sales that you need to decode the chip

**Comment by contractorwolf** [comment]
Explain to who? Is there no link for that feature? Any idea on the cost or have someones email I could talk to?

**Comment by lewisxhe** [comment]
I have reported the situation to Lilygo. I believe that there will be a corresponding purchase link soon. At present, please contact the staff of Quicksell and explain to them that you need a SIM7600 with a decoding chip
