### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by davidUKYFU** [Xinyuan-LilyGO/T-SIM7600X#92]
Hello,
I am doing a project in which I need maximum speed and I bought this device with the 150 mbps mark on mind. Nevertheless I found that I cannot reach even 100 kb/s of speed. I rode the datasheet of the 7600G and it declares up to 4 mbps of UART speed that is much lower but is better that what I have at this moment:

"Baud rate: 300bps to 4Mbps(default:115200bps)
Autobauding baud rate: 9600,19200,38400,57600,115200bps "

I tried to increase the UART_BAUD speed but it doesn't get higher than 115200bps. How can I get this baud rate higher or somehow increase the transfer speed?

Thank you in advance!

**Comment by felmue** [comment]
Hello @davidUKYFU 

have you tried `AT+IPR=?`command? It should return a list of supported speeds.

Thanks
Felix
