### ISSUE TITLE
[Question] - Pin 0 of NAU8810 chip in T-SIM7600X schematic sheet

### ISSUE THREAD

**Issue by PsySc0rpi0n** [Xinyuan-LilyGO/T-SIM7600X#94]
In the following file:
https://github.com/Xinyuan-LilyGO/T-SIM7600X/blob/master/schematic/T54_SIM7600_20201012.pdf

In page 2, there is a section with the audio chip NAU8810. According to the datasheet of this chip, there is no pin 0 (GND).
However in the said schematic, there is a pin 0. What is the purpose of this pin?
![image](https://github.com/user-attachments/assets/f8c6d8aa-4e23-4706-939b-3361404a1eaf)

From the datasheet here:
https://www.nuvoton.com/resource-files/NAU8810_Datasheet_Rev_2.8.pdf
page 98, there is no such pin.
![image](https://github.com/user-attachments/assets/f11d3bce-a615-463f-8c92-15e7bb5a85bd)

**Comment by X-Ryl669** [comment]
It's likely the thermal pad pin ("metal paddle VSSA" in the datasheet) that's used for connecting the chip thermal contact to the ground plane on the PCB. Just guessing here...

**Comment by lewisxhe** [comment]
@X-Ryl669 You are right, it is the heat sink pad at the bottom of the chip
